import { NextResponse } from 'next/server'
import satori from 'satori'
import { getAllNumbers, getConfig, getImageCache, setImageCache } from '@/lib/kv'
import type { NumbersMap } from '@/lib/types'
import { readFileSync } from 'fs'
import { join } from 'path'

// @resvg/resvg-js is imported dynamically so its native binary failures
// are caught and reported clearly instead of crashing module load at import time.

const CELL = 49
const GAP = 2
const GRID_PADDING = 14

const FONT_NAME = 'Inter'

function loadFont() {
  return [
    { name: FONT_NAME, data: readFileSync(join(process.cwd(), 'public/fonts/Inter-Regular.ttf')).buffer as ArrayBuffer, weight: 400 as const, style: 'normal' as const },
    { name: FONT_NAME, data: readFileSync(join(process.cwd(), 'public/fonts/Inter-Bold.ttf')).buffer as ArrayBuffer, weight: 700 as const, style: 'normal' as const },
  ]
}

/**
 * Read the hero image as a data URI.
 *
 * Prefers the pre-processed hero-circular.png (200×200 circle with transparent
 * background, generated by scripts/preprocess-hero.mjs at build time).
 * Falls back to the configured heroImageUrl if hero-circular.png does not exist.
 */
function readHeroDataUri(heroImageUrl: string): string | null {
  // Prefer pre-processed circular PNG
  const circularPath = join(process.cwd(), 'public', 'hero-circular.png')
  try {
    const buf = readFileSync(circularPath)
    return `data:image/png;base64,${buf.toString('base64')}`
  } catch {
    // Fall back to raw hero file (note: resvg does NOT support WebP data URIs)
    try {
      const filePath = join(process.cwd(), 'public', heroImageUrl.replace(/^\//, ''))
      const buf = readFileSync(filePath)
      const ext = heroImageUrl.split('.').pop()?.toLowerCase() || 'png'
      const mime = ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg' : 'image/png'
      return `data:${mime};base64,${buf.toString('base64')}`
    } catch {
      return null
    }
  }
}

/**
 * Inject the pre-cropped circular hero image into the SVG.
 *
 * The image is already a 200×200 circle with transparent background
 * (hero-circular.png), so no clipPath is needed — just position it.
 *
 * Satori layout: outer padding 24px top, 16px left; hero row marginTop: 10
 * Hero position → x=16, y=34 (24+10), size 200×200
 */
function injectHeroIntoSvg(svg: string, heroDataUri: string): string {
  const heroFragment =
    `<image href="${heroDataUri}" x="16" y="34" width="200" height="200" ` +
    `preserveAspectRatio="xMidYMid slice"/>`
  return svg.replace('</svg>', `${heroFragment}</svg>`)
}

function toRows(numbers: NumbersMap): { num: string; status: string }[][] {
  const entries = Object.entries(numbers).sort(([a], [b]) => a.localeCompare(b))
  const rows: { num: string; status: string }[][] = []
  for (let i = 0; i < 10; i++) {
    rows.push(entries.slice(i * 10, i * 10 + 10).map(([num, data]) => ({ num, status: data.status })))
  }
  return rows
}

export async function GET(request: Request) {
  const t0 = performance.now()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let Resvg: any = null
  let resvgError: unknown = null

  try {
    ;({ Resvg } = await import('@resvg/resvg-js'))
  } catch (err) {
    resvgError = err
    console.error('[raffle-image] resvg import failed:', err)
  }

  if (!Resvg) {
    const msg = resvgError instanceof Error ? resvgError.message : String(resvgError)
    return NextResponse.json({
      error: 'Image generation unavailable — resvg module failed to load',
      detail: msg,
    }, { status: 500 })
  }

  try {
    const refresh = new URL(request.url).searchParams.get('refresh') === '1'
    if (!refresh) {
      const cached = await getImageCache()
      if (cached) {
        const buf = Buffer.from(cached, 'base64')
        return new NextResponse(new Uint8Array(buf), {
          headers: { 'Content-Type': 'image/png', 'Cache-Control': 'public, max-age=3600' },
        })
      }
    }

    const [numbers, config] = await Promise.all([getAllNumbers(), getConfig()])
    if (!config) {
      return NextResponse.json({ error: 'Raffle not configured' }, { status: 500 })
    }
    const t1 = performance.now()
    console.log(`[raffle-image] data fetch: ${(t1 - t0).toFixed(0)}ms`)

    const heroDataUri = config.heroImageUrl ? readHeroDataUri(config.heroImageUrl) : null

    const fonts = loadFont()
    const rows = toRows(numbers)
    const hasHero = !!heroDataUri

    const svg = await satori(
      <div
        style={{
          width: 540, height: 960, backgroundColor: '#fff',
          display: 'flex', flexDirection: 'column', alignItems: 'center',
          padding: '24px 16px', fontFamily: FONT_NAME,
        }}
      >
        <div style={{ display: 'flex', gap: 14, marginTop: 10, alignSelf: 'flex-start' }}>
          {hasHero ? (
            // Transparent spacer — real hero image is injected as SVG <image> after satori
            <div style={{ width: 200, height: 200, flexShrink: 0 }} />
          ) : (
            <div style={{
              width: 200, height: 200, borderRadius: 100, backgroundColor: '#f1f5f9',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              overflow: 'hidden', flexShrink: 0,
            }}>
              <span style={{ fontSize: 60, color: '#64748b' }}>🎗️</span>
            </div>
          )}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            <span style={{ fontSize: 20, fontWeight: 700, color: '#1e293b' }}>
              {config.name}
            </span>
            <span style={{ fontSize: 12, color: '#64748b' }}>
              Beneficiaria: {config.beneficiary}
            </span>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {config.prizes.map((p) => (
                <div key={p.position} style={{
                  backgroundColor: '#fef2f2', borderRadius: 12, padding: '6px 12px',
                  display: 'flex', flexDirection: 'column', alignItems: 'center',
                }}>
                  <span style={{ fontSize: 10, color: '#dc2626', fontWeight: 600 }}>{p.position}° Premio</span>
                  <span style={{ fontSize: 15, fontWeight: 700, color: '#dc2626' }}>${p.amount}</span>
                </div>
              ))}
            </div>
            <span style={{ fontSize: 12, color: '#64748b' }}>Precio: ${config.ticketPrice}</span>
          </div>
        </div>

        <div style={{
          display: 'flex', flexDirection: 'column', gap: GAP, marginTop: 12,
          padding: GRID_PADDING, backgroundColor: '#f8fafc', borderRadius: 16, width: 508,
        }}>
          {rows.map((row, ri) => (
            <div key={ri} style={{ display: 'flex', gap: GAP }}>
              {row.map(({ num, status }) => {
                const isReserved = status === 'reserved'
                const isSold = status === 'sold'
                const bg = isSold ? '#dc2626' : isReserved ? '#f43f5e' : '#f1f5f9'
                const color = isReserved || isSold ? '#fff' : '#1e293b'
                return (
                  <div key={num} style={{
                    width: CELL, height: CELL, backgroundColor: bg, borderRadius: 8,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                  }}>
                    <span style={{ fontSize: 18, fontWeight: 700, color }}>
                      {num}
                    </span>
                  </div>
                )
              })}
            </div>
          ))}
        </div>

        <span style={{ fontSize: 12, color: '#64748b', marginTop: 14, textAlign: 'center' }}>
          Métodos de pago: Transferencia, Pago Móvil, Zelle
        </span>

        <span style={{ fontSize: 13, color: '#1e293b', fontWeight: 600, marginTop: 6, textAlign: 'center' }}>
          Sorteo: {config.drawDate} — {config.drawTime}
        </span>
        <span style={{ fontSize: 11, color: '#94a3b8', marginTop: 1 }}>{config.lottery}</span>

        <span style={{ marginTop: 'auto', fontSize: 11, color: '#cbd5e1', paddingBottom: 4 }}>
          rifa-solidaria.vercel.app
        </span>
      </div>,
      { width: 540, height: 960, fonts },
    )
    const t2 = performance.now()
    console.log(`[raffle-image] satori: ${(t2 - t1).toFixed(0)}ms`)

    // Debug: dump SVG if requested
    if (new URL(request.url).searchParams.get('debug') === 'svg') {
      const injectedSvg = heroDataUri ? injectHeroIntoSvg(svg, heroDataUri) : svg
      return new NextResponse(injectedSvg, {
        headers: { 'Content-Type': 'image/svg+xml' },
      })
    }

    // Inject circular hero image into SVG (avoids native module compositing)
    const finalSvg = heroDataUri ? injectHeroIntoSvg(svg, heroDataUri) : svg

    const pngBuffer = new Resvg(finalSvg, { fitTo: { mode: 'width', value: 540 } }).render().asPng()
    const t3 = performance.now()
    console.log(`[raffle-image] resvg + hero: ${(t3 - t2).toFixed(0)}ms`)

    const base64 = pngBuffer.toString('base64')
    await setImageCache(base64)

    return new NextResponse(new Uint8Array(pngBuffer), {
      headers: { 'Content-Type': 'image/png', 'Cache-Control': 'public, max-age=3600' },
    })
  } catch (error) {
    console.error('[raffle-image] Error generating raffle image:', error)
    const msg = error instanceof Error ? error.message : String(error)
    const stack = error instanceof Error ? error.stack : undefined
    return NextResponse.json({
      error: msg,
      ...(stack ? { stack: stack.split('\n').slice(0, 6).join('\n') } : {}),
      t: performance.now() - t0,
    }, { status: 500 })
  }
}
